POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Alvaro",
   "number": "27172213"
}

###
POST https://ejerciciosfullstackopen.onrender.com/api/persons
Content-Type: application/json

{
   "name": "Alvaro",
   "number": "27172213"
}